version: "3.9"

services:
  kali-gui:
    build: .
    restart: unless-stopped
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /dev/dri:/dev/dri
    devices:
      - /dev/dri
    privileged: true
